# Generated by Django 5.2.7 on 2025-10-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('Não alcoólica', 'Não alcoólica'), ('Cerveja', 'Cerveja'), ('Alcoólica', 'Alcoólica')], max_length=50, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço (R$)')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para venda')),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
                'ordering': ['nome'],
            },
        ),
    ]
