# Generated by Django 5.2.7 on 2025-10-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='gelada',
            field=models.BooleanField(default=True, verbose_name='Está Gelada?'),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='categoria',
            field=models.CharField(choices=[('Não alcoólica', 'Não alcoólica'), ('Cerveja', 'Cerveja'), ('Destilada', 'Destilada'), ('Vinho', 'Vinho/Espumante')], max_length=50, verbose_name='Categoria'),
        ),
    ]
