# Generated by Django 5.2.7 on 2025-11-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_bebida_gelada_alter_bebida_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebida',
            name='preco',
        ),
        migrations.AddField(
            model_name='bebida',
            name='descricao_fardo',
            field=models.CharField(blank=True, default='Fardo (12 unidades)', max_length=50, null=True, verbose_name='Descrição do Fardo'),
        ),
        migrations.AddField(
            model_name='bebida',
            name='preco_fardo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço (Fardo/Caixa)'),
        ),
        migrations.AddField(
            model_name='bebida',
            name='preco_unidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço (Unidade)'),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Produto (ex: Coca-Cola Lata 350ml)'),
        ),
    ]
