# Generated by Django 5.2.7 on 2025-11-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_remove_bebida_preco_bebida_descricao_fardo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebida',
            name='gelada',
        ),
        migrations.AlterField(
            model_name='bebida',
            name='categoria',
            field=models.CharField(choices=[('Cerveja Natural', 'Cerveja Natural'), ('Cerveja Gelada', 'Cerveja Gelada'), ('Refrigerante Gelado', 'Refrigerante Gelado'), ('Refrigerante Natural', 'Refrigerante Natural'), ('Destilada', 'Destilada')], max_length=50, verbose_name='Categoria'),
        ),
    ]
